version: '3.8'

services:
  # Service 1: Database PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: portfolio_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: portfolio_db
    ports:
      - "5433:5432"
    volumes:
      # Volume ini penting agar tidak hilang saat container dimatikan
      - postgres_data:/var/lib/postgresql/data

  # Service 2: pgAdmin (Interface Web untuk Kelola Database)
  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

# Definisi Volume
volumes:
  postgres_data: